services:
  app:
    build: .
    container_name: coffee-shop-app
    ports:
      - "8001:8000" # 8000 is used by another app on my mac
    environment:
      - DATABASE_URL=postgresql+asyncpg://coffee_shop:coffee_shop@db:5432/coffee_shop
      - SECRET_KEY=your-super-secret-key-change-in-production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=15
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15-alpine
    container_name: coffee-shop-db
    environment:
      - POSTGRES_USER=coffee_shop
      - POSTGRES_PASSWORD=coffee_shop
      - POSTGRES_DB=coffee_shop
    ports:
      - "5434:5432" # 5432, 5433 is used by another app on my mac
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U coffee_shop" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: coffee-shop-redis
    ports:
      - "6380:6379" # 6379 is used by another app on my mac

  celery-worker:
    build: .
    container_name: coffee-shop-celery-worker
    command: celery -A celery_app.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql+asyncpg://coffee_shop:coffee_shop@db:5432/coffee_shop
      - SECRET_KEY=your-super-secret-key-change-in-production
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  celery-beat:
    build: .
    container_name: coffee-shop-celery-beat
    command: celery -A celery_app.celery beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql+asyncpg://coffee_shop:coffee_shop@db:5432/coffee_shop
      - SECRET_KEY=your-super-secret-key-change-in-production
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

volumes:
  postgres_data:
